name: 'Check Changelog'
description: 'Check for changelog entry on PR and comment with status'
author: 'wevm'

inputs:
  ai:
    description: 'AI command to generate changelog (must accept stdin)'
    required: false
  ref:
    description: 'Base ref to compare against'
    required: false
    default: ${{ github.base_ref }}
  token:
    description: 'GitHub token for commenting on PR'
    required: false
    default: ${{ github.token }}

outputs:
  found:
    description: 'Whether a changelog was found on the PR'
    value: ${{ steps.check.outputs.found }}

runs:
  using: 'composite'
  steps:
    - name: Check for changelog
      id: check
      shell: bash
      run: |
        CHANGELOGS=$(git diff --name-only origin/${{ inputs.ref }}...HEAD -- '.changelog/*.md' | grep -v config.toml || true)
        if [ -n "$CHANGELOGS" ]; then
          echo "found=true" >> $GITHUB_OUTPUT
          echo "changelog_files=$CHANGELOGS" >> $GITHUB_OUTPUT
        else
          echo "found=false" >> $GITHUB_OUTPUT
        fi

    - name: Install changelogs
      if: steps.check.outputs.found == 'false' && inputs.ai != ''
      shell: bash
      run: curl -sSL https://changelogs.sh | sh

    - name: Generate changelog with AI
      id: ai
      if: steps.check.outputs.found == 'false' && inputs.ai != ''
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        
        # Run changelogs add with AI, capture the generated file
        changelogs add --ai "${{ inputs.ai }}" --ref origin/${{ inputs.ref }}
        
        # Find the generated changelog file
        GENERATED_FILE=$(ls -t .changelog/*.md | grep -v README.md | head -n1)
        if [ -n "$GENERATED_FILE" ]; then
          CONTENT=$(cat "$GENERATED_FILE")
          # Clean up - we only wanted to generate, not keep
          rm "$GENERATED_FILE"
          
          # Write to temp file for later use
          echo "$CONTENT" > /tmp/ai_changelog.md
          echo "generated=true" >> $GITHUB_OUTPUT
        else
          echo "generated=false" >> $GITHUB_OUTPUT
        fi

    - name: Build comment body
      id: body
      shell: bash
      run: |
        REPO="${{ github.repository }}"
        HEAD_REF="${{ github.head_ref }}"
        
        if [ "${{ steps.check.outputs.found }}" = "true" ]; then
          # Changelog found - show edit link
          CHANGELOG_FILE=$(echo "${{ steps.check.outputs.changelog_files }}" | head -n1)
          EDIT_URL="https://github.com/${REPO}/edit/${HEAD_REF}/${CHANGELOG_FILE}"
          
          BODY="### ✅ Changelog found on PR.

        [Edit changelog](${EDIT_URL})"
        else
          # No changelog - build template
          if [ "${{ steps.ai.outputs.generated }}" = "true" ]; then
            TEMPLATE=$(cat /tmp/ai_changelog.md)
            AI_GENERATED=true
          else
            TEMPLATE="---
        <package-name>: patch
        ---

        Brief description of changes."
            AI_GENERATED=false
          fi
          
          # URL encode the template
          ENCODED_TEMPLATE=$(python3 -c "import urllib.parse; import sys; print(urllib.parse.quote(sys.stdin.read()))" < <(echo "$TEMPLATE"))
          
          # Generate a random ID for the new changelog file
          CHANGELOG_ID=$(head -c 100 /dev/urandom | LC_ALL=C tr -dc 'a-z' | head -c 8)
          NEW_FILE=".changelog/${CHANGELOG_ID}.md"
          ADD_URL="https://github.com/${REPO}/new/${HEAD_REF}?filename=${NEW_FILE}&value=${ENCODED_TEMPLATE}"
          
          if [ "$AI_GENERATED" = "true" ]; then
            BODY="### ⚠️ Changelog not found.

        A changelog entry is required before merging. We've generated a suggested changelog based on your changes:

        <details>
        <summary>Preview</summary>

        \`\`\`markdown
        ${TEMPLATE}
        \`\`\`

        </details>

        **[Add changelog](${ADD_URL})** to commit this to your branch."
          else
            BODY="### ⚠️ Changelog not found.

        A changelog entry is required before merging.

        **[Add changelog](${ADD_URL})**"
          fi
        fi
        
        # Write to file for multiline support
        echo "$BODY" > /tmp/comment_body.md

    - name: Find existing comment
      id: find
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        COMMENT_ID=$(gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
          --jq '.[] | select(.body | startswith("### ✅ Changelog") or startswith("### ⚠️ Changelog")) | .id' \
          | head -n1)
        echo "comment_id=$COMMENT_ID" >> $GITHUB_OUTPUT

    - name: Create or update comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        BODY=$(cat /tmp/comment_body.md)
        
        if [ -n "${{ steps.find.outputs.comment_id }}" ]; then
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/issues/comments/${{ steps.find.outputs.comment_id }}" \
            -f body="$BODY"
        else
          gh pr comment ${{ github.event.pull_request.number }} --body "$BODY"
        fi
