name: 'Generate Changelog'
description: 'Check for missing changelog and generate'
author: 'wevm'

inputs:
  ai:
    description: 'AI command to generate changelog (must accept stdin)'
    required: true
  ref:
    description: 'Base ref to compare against'
    required: false
    default: ${{ github.base_ref }}
  message:
    description: 'Commit message for the changelog'
    required: false
    default: 'chore: add changelog'
  instructions:
    description: 'Custom instructions for AI generation (use {packages} and {diff} placeholders)'
    required: false

outputs:
  found:
    description: 'Whether a changelog was already present'
    value: ${{ steps.check.outputs.found }}
  generated:
    description: 'Whether a changelog was generated'
    value: ${{ steps.generate.outputs.generated }}

runs:
  using: 'composite'
  steps:
    - name: Check for changelog
      id: check
      shell: bash
      run: |
        CHANGELOGS=$(git diff --name-only origin/${{ inputs.ref }}...HEAD -- '.changelog/*.md' | grep -v config.toml || true)
        if [ -n "$CHANGELOGS" ]; then
          echo "found=true" >> $GITHUB_OUTPUT
          echo "Changelog found: $CHANGELOGS"
        else
          echo "found=false" >> $GITHUB_OUTPUT
          echo "No changelog found"
        fi

    - name: Generate changelog
      id: generate
      if: steps.check.outputs.found == 'false'
      shell: bash
      run: |
        ARGS="--ai \"${{ inputs.ai }}\" --ref origin/${{ inputs.ref }}"
        if [ -n "${{ inputs.instructions }}" ]; then
          ARGS="$ARGS --instructions \"${{ inputs.instructions }}\""
        fi
        eval "changelogs add $ARGS"
        echo "generated=true" >> $GITHUB_OUTPUT

    - name: Commit changelog
      if: steps.check.outputs.found == 'false'
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .changelog/
        git commit -m "${{ inputs.message }}"
        git push
